name: Docker Image tag
on: workflow_dispatch

jobs:
  repo_info:
    runs-on: ubuntu-latest
    env:
      test: 'my-world'
    steps:
      - name: var echo
        run: echo ${{ env.test }}  
  
    
