name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [18,20]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ martrix.operating-system }}
    steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install depenedencies
      run: npm ci
    - name: build project
      run: npm run  build
