name: SCI008-SCA-Scanning
on:
  workflow_dispatch:
    inputs:
      FEATURE_BRANCH_NAME:
        description: 'Freature Branch name that need to be scanned'
        required: false
        type: string
        default: main
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
         echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "${GITHUB_OUTPUT}"
         echo "sanitized_branch=${GITHUB_REF_NAME/\//-}" >> "${GITHUB_OUTPUT}"
    outputs:
     sanitized_branch: ${{ steps.extract_branch.outputs.sanitized_branch }}
