name: sanitize branch test
on:
  workflow_dispatch:
    inputs:
      FEATURE_BRANCH_NAME:
        description: 'Freature Branch name that need to be scanned'
        required: false
        type: string
        default: main
  
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    name: "build"
    needs: [init]
    steps:
        # Checkout the code
        - name: Checkout
          uses: actions/checkout@v4
          with:
            # Disabling shallow clones is recommended for improving the relevancy of reporting
            fetch-depth: 0
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: extract_branch
        run: |
         echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "${GITHUB_OUTPUT}"
         echo "sanitized_branch=${GITHUB_REF_NAME/\//-}" >> "${GITHUB_OUTPUT}"
      - name: CX scan Project version
        
        id: cx-scan-project-version
        run: |
          if [[ ${{ github.ref_type == 'tag' }} ]]; then
              echo "CX_VERSION=-${{ steps.extract_branch.outputs.sanitized_branch }}" >> $GITHUB_OUTPUT
          else
              echo "CX_VERSION=" >> $GITHUB_OUTPUT
          fi
      - name: echo
        run: | 
          echo "cncp-secret-management-${{ needs.init.outputs.branch }}"
           echo
    outputs:
     sanitized_branch: ${{ steps.extract_branch.outputs.sanitized_branch }}
     CX_VERSION: cncp-secret-management-${{ steps.cx-scan-project-version.outputs.CX_VERSION }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
         # echo "cncp-secret-management${{ needs.init.outputs.CX_VERSION }}"
         echo 
         
